/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuideUtilisateur.java
 *
 * Created on 24 mai 2012, 11:15:13
 */
package sipee;

/**
 *
 * @author admine
 */
public class GuideUtilisateur extends javax.swing.JInternalFrame {

    /** Creates new form GuideUtilisateur */
    public GuideUtilisateur() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Guide d'utilisation de SIPEEsoft");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 3, 12));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("                        1-Introduction\n    Ce guide fournit les instructions nécessaires à l'installation de SIPEEsoft, à la \nconnexion de votre modem GSM ou votre téléphone GSM à votre PC \net à l'utilisation des applications de SIPEEsoft.\n\n                        2-Applications de SIPEEsoft\n    Avec SIPEEsoft,vous pouvez envoyez des SMS aux enseignants et aux parents d'élèves sur leurs\ntéléphone portable. De plus vous pouvez inscrire et stocker les informations sur les élèves,\nles enseignant et les parents d'élèves.\nSIPEEsoft est compose de plusieurs applications. ");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
