/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PageAccueil.java
 *
 * Created on 15 mai 2012, 00:53:46
 */

package sipee;

import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JInternalFrame;

/**
 *
 * @author admine
 */
public class PageAccueil extends javax.swing.JInternalFrame {

    /** Creates new form PageAccueil */
    public static final int x = (int) Toolkit.getDefaultToolkit().getScreenSize().width;
    public static final int y = (int) Toolkit.getDefaultToolkit().getScreenSize().height;

    public PageAccueil() {
        initComponents();
        //pleinEcran(this);
        //this.setVisible(true);
        this.setSize(MainFrame.jDesktopPane1.getWidth(), MainFrame.jDesktopPane1.getHeight());
    }
    public void pleinEcran(JInternalFrame fenetre) {
        int Xf = (int) fenetre.getSize().getWidth();
        int Yf = (int) fenetre.getSize().getHeight();
        fenetre.setBounds(0, 0, x, y - 30);
        // fenetre.setLocation(x,y);
        //  fenetre.setVisible(true);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageAcc1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
